services:
  johnson-bot:
    image: beanbubger/johnson-rs:main
    container_name: johnson-rs
    restart: always
    environment:
      - TOKEN=${TOKEN}
      - LEVEL=PROD
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - sqlitedb:/usr/local/db
    profiles: [release]

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 johnson-rs
    profiles: [release]

  debug-johnson-bot:
    build: .
    container_name: debug-johnson-rs
    environment:
      - TOKEN=${TOKEN}
      - LEVEL=DEBUG
      - DATABASE_URL=sqlite:///usr/local/db/johnson.db
    volumes:
      - sqlitedb:/usr/local/db
    profiles: [debug]

volumes:
  sqlitedb:
