version: "3.8"

services:

  mongo:
    image: mongo
    container_name: johnson-mongo
    restart: always
    ports:
      - 27017:27017

  main:
    build: .
    container_name: johnson-rs
    restart: always
    depends_on:
      - mongo
    environment:
      - TOKEN=${TOKEN}
      - RSPOTIFY_CLIENT_ID=${RSPOTIFY_CLIENT_ID}
      - RSPOTIFY_CLIENT_SECRET=${RSPOTIFY_CLIENT_SECRET}
      - RSPOTIFY_REDIRECT_URI
      - MONGO_CONN_URL=${MONGO_CONN_URL}
      # - RUST_BACKTRACE=full
      - LEVEL



