version: "3.8"

services:

  main:
    build: .
    container_name: johnson-rs
    restart: always
    environment:
      - TOKEN=${TOKEN}
      - RSPOTIFY_CLIENT_ID=${RSPOTIFY_CLIENT_ID}
      - RSPOTIFY_CLIENT_SECRET=${RSPOTIFY_CLIENT_SECRET}
      - RSPOTIFY_REDIRECT_URI
      - MONGO_CONN=${MONGO_CONN}
      - LEVEL

  mongo:
    image: mongo
    container_name: johnson-mongo
    restart: always
    ports:
      - 27017:27017


